export const PRESENTATION_KEYS = {
  LATA: 'lata',
  LATON: 'laton',
  MEGALATON: 'megalaton',
  CAGUAMA: 'caguama',
  CAGUAMON: 'caguamon',
  BOTELLA: 'botella',
  CUARTITO: 'cuartito',
};

export const PRESENTATION_LABELS = {
  [PRESENTATION_KEYS.LATA]: 'Lata',
  [PRESENTATION_KEYS.LATON]: 'Laton',
  [PRESENTATION_KEYS.MEGALATON]: 'Megalaton',
  [PRESENTATION_KEYS.CAGUAMA]: 'Caguama',
  [PRESENTATION_KEYS.CAGUAMON]: 'Caguamon',
  [PRESENTATION_KEYS.BOTELLA]: 'Botella',
  [PRESENTATION_KEYS.CUARTITO]: 'Cuartito',
};

export const PRESENTATION_ORDER = [
  PRESENTATION_KEYS.LATA,
  PRESENTATION_KEYS.LATON,
  PRESENTATION_KEYS.MEGALATON,
  PRESENTATION_KEYS.CAGUAMA,
  PRESENTATION_KEYS.CAGUAMON,
  PRESENTATION_KEYS.BOTELLA,
  PRESENTATION_KEYS.CUARTITO,
];
